import { createContext, useContext, useEffect, useState, ReactNode } from "react";

export type Lang = "en" | "hr" | "es" | "de" | "fr" | "it";

export const LANGUAGES: { code: Lang; name: string; flag: string }[] = [
  { code: "en", name: "English", flag: "🇬🇧" },
  { code: "hr", name: "Hrvatski", flag: "🇭🇷" },
  { code: "es", name: "Español", flag: "🇪🇸" },
  { code: "de", name: "Deutsch", flag: "🇩🇪" },
  { code: "fr", name: "Français", flag: "🇫🇷" },
  { code: "it", name: "Italiano", flag: "🇮🇹" },
];

type Dict = Record<string, string>;

const en: Dict = {
  // nav
  "nav.court": "Court",
  "nav.leagues": "Leagues",
  "nav.profile": "Profile",
  // common
  "common.back": "Back",
  "common.loading": "Loading…",
  "common.save": "Save",
  "common.cancel": "Cancel",
  "common.close": "Close",
  "common.create": "Create",
  "common.delete": "Delete",
  "common.optional": "optional",
  "common.opt": "opt.",
  "common.away": "away",
  "common.skip": "Skip for now",
  // settings
  "settings.title": "Settings",
  "settings.appearance": "Appearance",
  "settings.language": "Language",
  "settings.day": "Day mode",
  "settings.night": "Night mode",
  "settings.radius": "Discovery radius",
  "settings.radius.courts": "Courts within",
  "settings.radius.hoopers": "Hoopers within",
  // language picker
  "lang.pick.title": "Choose your language",
  "lang.pick.sub": "You can change this later in Settings.",
  "lang.continue": "Continue",
  // home
  "home.live": "Live",
  "home.off": "Off",
  "home.on": "On",
  "home.hoopers_nearby": "Hoopers nearby",
  "home.active_courts": "Active courts",
  "home.courts_near": "Courts near you",
  "home.add": "Add",
  "home.mark_first": "Mark your first court",
  "home.hooper": "hooper",
  "home.hoopers": "hoopers",
  "home.hoopers_near": "Hoopers near you",
  "home.empty.title": "Court's empty",
  "home.empty.sub": "No hoopers around yet. Invite friends to join Hoops and they'll show up here.",
  "home.court.mark": "Mark a court",
  "home.court.pinned": "Pinned at your current location.",
  "home.court.name_ph": "Court name (e.g. West Park)",
  "home.court.add_btn": "Add court",
  "home.court.saving": "Saving…",
  "home.gmaps": "Google Maps",
  "home.here": "here",
  // player
  "player.location_unknown": "Location unknown",
  "player.rating": "rating",
  "player.ratings": "ratings",
  "player.callup": "🏀 Call up for a hoop sesh",
  "player.invite": "Invite",
  "player.invite_to": "Invite",
  "player.send_invite": "Send invite",
  "player.cant_rate": "You can rate this player after you play together (logged league game) or once they accept your hoop sesh invite.",
  "player.update_rating": "Update rating",
  "player.rate": "Rate this player",
  "player.how_hoop": "How they hoop",
  "player.offense": "Offense",
  "player.defense": "Defense",
  "player.save_rating": "Save rating",
  "player.invite_default": "Yo, run it? 🏀",
  "player.invite_ph": "Court, time, vibe…",
  "player.back_court": "Back to court",
  "player.invite_sent": "Invite sent",
  // profile
  "profile.username": "Username",
  "profile.phone": "Phone",
  "profile.height": "Height (cm)",
  "profile.vertical": "Vertical (cm)",
  "profile.weight": "Weight (kg)",
  "profile.playstyle": "Playstyle",
  "profile.visible": "visible",
  "profile.pick_archetype": "Pick your archetype",
  "profile.preferred_game": "Preferred game type",
  "profile.pick_one": "Pick one",
  "profile.shooting_drills": "Shooting drills",
  "profile.signout": "Sign out",
  "profile.saved": "Profile saved",
  // leagues
  "leagues.title": "LEAGUES",
  "leagues.sub": "Run with your crew. Track every dub.",
  "leagues.invites": "Invites",
  "leagues.from": "from",
  "leagues.accept": "Accept",
  "leagues.decline": "Decline",
  "leagues.create": "Create league",
  "leagues.join_code": "Join with code",
  "leagues.your": "Your leagues",
  "leagues.none": "No leagues yet",
  "leagues.none_sub": "Create one with your usual crew or join one with a code.",
  "leagues.code": "Code",
  "leagues.new": "New league",
  "leagues.name": "League name",
  "leagues.name_ph": "Sunday Run",
  "leagues.join": "Join a league",
  "leagues.join_field": "Join code",
  "leagues.join_btn": "Join",
  "leagues.joined": "Joined league",
  "leagues.created": "League created",
  "leagues.declined": "Declined",
  "leagues.not_found": "League not found",
  "leagues.invalid_code": "Invalid code",
  "leagues.name_short": "Name too short",
  // league detail
  "ld.code_copied": "Code copied",
  "ld.log_game": "Log game",
  "ld.game_type": "Game type",
  "ld.all": "All",
  "ld.show_lb": "Showing {type} leaderboard only.",
  "ld.koth_note": "King of the Hill — individual stats only, no team records.",
  "ld.tab_players": "Players",
  "ld.tab_teams": "Teams",
  "ld.tab_games": "Games",
  "ld.no_stats": "No stats yet — log your first game.",
  "ld.no_team_records": "No team records yet.",
  "ld.no_games": "No games logged yet.",
  "ld.invite_players": "Invite players",
  "ld.search_user": "Search username…",
  "ld.type_2": "Type at least 2 characters.",
  "ld.no_match": "No matching users.",
  "ld.invite": "Invite",
  "ld.already_invited": "Already invited",
  "ld.invite_sent": "Invite sent",
  // log game
  "log.title": "Log a game",
  "log.team_a": "Team A",
  "log.team_b": "Team B",
  "log.location": "Location",
  "log.location_ph": "Rucker Park",
  "log.players_stats": "Players & stats",
  "log.no_members": "No members yet — share the league code so your crew can join.",
  "log.save": "Save game",
  "log.pick_2": "Pick at least 2 players",
  "log.each_team": "Each team needs at least one player",
  "log.logged": "Game logged 🏀",
  // drills
  "drills.title": "Shooting drills",
  "drills.private": "Private — only you see this.",
  "drills.selected": "Selected zone",
  "drills.no_attempts": "No attempts yet",
  "drills.made": "Made",
  "drills.attempts": "Attempts",
  "drills.log": "Log shots",
  "drills.history": "History",
  "drills.empty": "No drills yet — pick a spot and log your first set.",
  "drills.logged": "Drill logged",
  "drills.removed": "Removed",
  "drills.makes_exceed": "Makes can't exceed attempts",
  // auth
  "auth.tag": "Run it back. Find your next sesh.",
  "auth.signup": "Sign up",
  "auth.login": "Log in",
  "auth.email": "Email",
  "auth.password": "Password",
  "auth.lace_up": "Lace up",
  "auth.check_in": "Check in",
  "auth.terms": "By signing up you agree to share your location and receive notifications about hoop seshes.",
  "auth.welcome": "Welcome to Hoops 🏀",
  "auth.username_taken": "Username already taken",
  "auth.phone_used": "Phone number already in use",
  // toasts / generic
  "toast.failed": "Failed",
  "toast.something": "Something went wrong",
  "toast.court_added": "Court added at your location",
  // 404
  "nf.title": "Out of bounds",
  "nf.sub": "That page isn't on the court.",
  "nf.back": "Back to Hoops",
  "err.title": "Airball.",
  "err.try": "Try again",
};

const hr: Dict = {
  "nav.court": "Teren", "nav.leagues": "Lige", "nav.profile": "Profil",
  "common.back": "Natrag", "common.loading": "Učitavanje…", "common.save": "Spremi", "common.cancel": "Odustani",
  "common.close": "Zatvori", "common.create": "Stvori", "common.delete": "Obriši", "common.optional": "opcionalno",
  "common.opt": "opc.", "common.away": "udaljeno", "common.skip": "Preskoči",
  "settings.title": "Postavke", "settings.appearance": "Izgled", "settings.language": "Jezik",
  "settings.day": "Dnevni način", "settings.night": "Noćni način",
  "settings.radius": "Radijus pretrage", "settings.radius.courts": "Tereni unutar", "settings.radius.hoopers": "Igrači unutar",
  "lang.pick.title": "Odaberi jezik", "lang.pick.sub": "Možeš ga promijeniti kasnije u postavkama.", "lang.continue": "Nastavi",
  "home.live": "Uživo", "home.off": "Isključeno", "home.on": "Uključeno",
  "home.hoopers_nearby": "Igrača blizu", "home.active_courts": "Aktivnih terena",
  "home.courts_near": "Tereni blizu tebe", "home.add": "Dodaj",
  "home.mark_first": "Označi svoj prvi teren", "home.hooper": "igrač", "home.hoopers": "igrača",
  "home.hoopers_near": "Igrači blizu tebe",
  "home.empty.title": "Teren je prazan", "home.empty.sub": "Još nema igrača u blizini. Pozovi prijatelje na Hoops i pojavit će se ovdje.",
  "home.court.mark": "Označi teren", "home.court.pinned": "Postavljeno na tvoju trenutnu lokaciju.",
  "home.court.name_ph": "Naziv terena (npr. Park Zapad)", "home.court.add_btn": "Dodaj teren", "home.court.saving": "Spremanje…",
  "home.gmaps": "Google karte", "home.here": "ovdje",
  "player.location_unknown": "Nepoznata lokacija", "player.rating": "ocjena", "player.ratings": "ocjena",
  "player.callup": "🏀 Pozovi na košarku", "player.invite": "Pozovi", "player.invite_to": "Pozovi",
  "player.send_invite": "Pošalji poziv",
  "player.cant_rate": "Možeš ocijeniti igrača nakon što odigrate zajedno (zabilježena utakmica) ili kad prihvati tvoj poziv na košarku.",
  "player.update_rating": "Ažuriraj ocjenu", "player.rate": "Ocijeni igrača", "player.how_hoop": "Kako igra",
  "player.offense": "Napad", "player.defense": "Obrana", "player.save_rating": "Spremi ocjenu",
  "player.invite_default": "Idemo na koš? 🏀", "player.invite_ph": "Teren, vrijeme, vibra…",
  "player.back_court": "Natrag na teren", "player.invite_sent": "Poziv poslan",
  "profile.username": "Korisničko ime", "profile.phone": "Telefon", "profile.height": "Visina (cm)",
  "profile.vertical": "Vertikalni skok (cm)", "profile.weight": "Težina (kg)", "profile.playstyle": "Stil igre",
  "profile.visible": "vidljivo", "profile.pick_archetype": "Odaberi arhetip",
  "profile.preferred_game": "Preferirani tip igre", "profile.pick_one": "Odaberi",
  "profile.shooting_drills": "Vježbe šuta", "profile.signout": "Odjavi se", "profile.saved": "Profil spremljen",
  "leagues.title": "LIGE", "leagues.sub": "Igraj sa svojom ekipom. Prati svaku pobjedu.",
  "leagues.invites": "Pozivi", "leagues.from": "od",
  "leagues.accept": "Prihvati", "leagues.decline": "Odbij",
  "leagues.create": "Stvori ligu", "leagues.join_code": "Pridruži se kodom",
  "leagues.your": "Tvoje lige", "leagues.none": "Još nema liga",
  "leagues.none_sub": "Stvori jednu sa svojom ekipom ili se pridruži kodom.",
  "leagues.code": "Kod", "leagues.new": "Nova liga", "leagues.name": "Naziv lige",
  "leagues.name_ph": "Nedjeljna ekipa", "leagues.join": "Pridruži se ligi", "leagues.join_field": "Kod za pristup",
  "leagues.join_btn": "Pridruži se", "leagues.joined": "Pridružio si se ligi", "leagues.created": "Liga stvorena",
  "leagues.declined": "Odbijeno", "leagues.not_found": "Liga nije pronađena",
  "leagues.invalid_code": "Neispravan kod", "leagues.name_short": "Naziv prekratak",
  "ld.code_copied": "Kod kopiran", "ld.log_game": "Zabilježi utakmicu", "ld.game_type": "Tip igre", "ld.all": "Sve",
  "ld.show_lb": "Prikazujem {type} ljestvicu.",
  "ld.koth_note": "King of the Hill — samo individualne statistike, bez timskih rekorda.",
  "ld.tab_players": "Igrači", "ld.tab_teams": "Timovi", "ld.tab_games": "Utakmice",
  "ld.no_stats": "Još nema statistika — zabilježi prvu utakmicu.",
  "ld.no_team_records": "Još nema timskih rekorda.", "ld.no_games": "Još nema zabilježenih utakmica.",
  "ld.invite_players": "Pozovi igrače", "ld.search_user": "Pretraži korisničko ime…",
  "ld.type_2": "Upiši najmanje 2 znaka.", "ld.no_match": "Nema rezultata.",
  "ld.invite": "Pozovi", "ld.already_invited": "Već pozvan", "ld.invite_sent": "Poziv poslan",
  "log.title": "Zabilježi utakmicu", "log.team_a": "Tim A", "log.team_b": "Tim B",
  "log.location": "Lokacija", "log.location_ph": "Rucker Park", "log.players_stats": "Igrači i statistika",
  "log.no_members": "Još nema članova — podijeli kod lige da ti se ekipa pridruži.",
  "log.save": "Spremi utakmicu", "log.pick_2": "Odaberi barem 2 igrača",
  "log.each_team": "Svaki tim treba barem jednog igrača", "log.logged": "Utakmica zabilježena 🏀",
  "drills.title": "Vježbe šuta", "drills.private": "Privatno — samo ti ovo vidiš.",
  "drills.selected": "Odabrana zona", "drills.no_attempts": "Još nema pokušaja",
  "drills.made": "Pogodaka", "drills.attempts": "Pokušaja", "drills.log": "Zabilježi šuteve",
  "drills.history": "Povijest", "drills.empty": "Još nema vježbi — odaberi mjesto i zabilježi prvu seriju.",
  "drills.logged": "Vježba zabilježena", "drills.removed": "Uklonjeno",
  "drills.makes_exceed": "Pogodci ne mogu biti veći od pokušaja",
  "auth.tag": "Vrati se na teren. Nađi svoju iduću ekipu.",
  "auth.signup": "Registracija", "auth.login": "Prijava",
  "auth.email": "Email", "auth.password": "Lozinka",
  "auth.lace_up": "Veži tenisice", "auth.check_in": "Prijavi se",
  "auth.terms": "Registracijom pristaješ na dijeljenje lokacije i primanje obavijesti o košarci.",
  "auth.welcome": "Dobrodošao u Hoops 🏀",
  "auth.username_taken": "Korisničko ime zauzeto", "auth.phone_used": "Broj telefona već u upotrebi",
  "toast.failed": "Greška", "toast.something": "Nešto je pošlo po zlu", "toast.court_added": "Teren dodan na tvojoj lokaciji",
  "nf.title": "Izvan terena", "nf.sub": "Te stranice nema na terenu.", "nf.back": "Natrag u Hoops",
  "err.title": "Promašaj.", "err.try": "Pokušaj ponovno",
};

const es: Dict = {
  "nav.court": "Cancha", "nav.leagues": "Ligas", "nav.profile": "Perfil",
  "common.back": "Atrás", "common.loading": "Cargando…", "common.save": "Guardar", "common.cancel": "Cancelar",
  "common.close": "Cerrar", "common.create": "Crear", "common.delete": "Eliminar", "common.optional": "opcional",
  "common.opt": "opc.", "common.away": "de distancia", "common.skip": "Saltar",
  "settings.title": "Ajustes", "settings.appearance": "Apariencia", "settings.language": "Idioma",
  "settings.day": "Modo día", "settings.night": "Modo noche",
  "settings.radius": "Radio de descubrimiento", "settings.radius.courts": "Canchas en", "settings.radius.hoopers": "Jugadores en",
  "lang.pick.title": "Elige tu idioma", "lang.pick.sub": "Puedes cambiarlo luego en Ajustes.", "lang.continue": "Continuar",
  "home.live": "En vivo", "home.off": "Off", "home.on": "On",
  "home.hoopers_nearby": "Jugadores cerca", "home.active_courts": "Canchas activas",
  "home.courts_near": "Canchas cerca de ti", "home.add": "Añadir",
  "home.mark_first": "Marca tu primera cancha", "home.hooper": "jugador", "home.hoopers": "jugadores",
  "home.hoopers_near": "Jugadores cerca de ti",
  "home.empty.title": "Cancha vacía", "home.empty.sub": "Aún no hay jugadores cerca. Invita amigos a Hoops y aparecerán aquí.",
  "home.court.mark": "Marcar cancha", "home.court.pinned": "Fijada en tu ubicación actual.",
  "home.court.name_ph": "Nombre (ej. Parque Oeste)", "home.court.add_btn": "Añadir cancha", "home.court.saving": "Guardando…",
  "home.gmaps": "Google Maps", "home.here": "aquí",
  "player.location_unknown": "Ubicación desconocida", "player.rating": "valoración", "player.ratings": "valoraciones",
  "player.callup": "🏀 Llamar para una pachanga", "player.invite": "Invitar", "player.invite_to": "Invitar",
  "player.send_invite": "Enviar invitación",
  "player.cant_rate": "Puedes valorar a este jugador después de jugar juntos o cuando acepte tu invitación.",
  "player.update_rating": "Actualizar valoración", "player.rate": "Valorar jugador", "player.how_hoop": "Cómo juega",
  "player.offense": "Ataque", "player.defense": "Defensa", "player.save_rating": "Guardar valoración",
  "player.invite_default": "¿Jugamos? 🏀", "player.invite_ph": "Cancha, hora, vibra…",
  "player.back_court": "Volver a la cancha", "player.invite_sent": "Invitación enviada",
  "profile.username": "Usuario", "profile.phone": "Teléfono", "profile.height": "Altura (cm)",
  "profile.vertical": "Salto vertical (cm)", "profile.weight": "Peso (kg)", "profile.playstyle": "Estilo de juego",
  "profile.visible": "visible", "profile.pick_archetype": "Elige tu arquetipo",
  "profile.preferred_game": "Tipo de juego preferido", "profile.pick_one": "Elige uno",
  "profile.shooting_drills": "Ejercicios de tiro", "profile.signout": "Cerrar sesión", "profile.saved": "Perfil guardado",
  "leagues.title": "LIGAS", "leagues.sub": "Juega con tu crew. Registra cada victoria.",
  "leagues.invites": "Invitaciones", "leagues.from": "de",
  "leagues.accept": "Aceptar", "leagues.decline": "Rechazar",
  "leagues.create": "Crear liga", "leagues.join_code": "Unirse con código",
  "leagues.your": "Tus ligas", "leagues.none": "Aún sin ligas",
  "leagues.none_sub": "Crea una con tu crew o únete con un código.",
  "leagues.code": "Código", "leagues.new": "Nueva liga", "leagues.name": "Nombre de la liga",
  "leagues.name_ph": "Pachanga del domingo", "leagues.join": "Unirse a una liga", "leagues.join_field": "Código",
  "leagues.join_btn": "Unirse", "leagues.joined": "Te uniste a la liga", "leagues.created": "Liga creada",
  "leagues.declined": "Rechazada", "leagues.not_found": "Liga no encontrada",
  "leagues.invalid_code": "Código inválido", "leagues.name_short": "Nombre muy corto",
  "ld.code_copied": "Código copiado", "ld.log_game": "Registrar partido", "ld.game_type": "Tipo", "ld.all": "Todos",
  "ld.show_lb": "Mostrando clasificación {type}.",
  "ld.koth_note": "King of the Hill — solo estadísticas individuales.",
  "ld.tab_players": "Jugadores", "ld.tab_teams": "Equipos", "ld.tab_games": "Partidos",
  "ld.no_stats": "Sin estadísticas — registra tu primer partido.",
  "ld.no_team_records": "Sin récords de equipo.", "ld.no_games": "Sin partidos registrados.",
  "ld.invite_players": "Invitar jugadores", "ld.search_user": "Buscar usuario…",
  "ld.type_2": "Escribe al menos 2 caracteres.", "ld.no_match": "Sin resultados.",
  "ld.invite": "Invitar", "ld.already_invited": "Ya invitado", "ld.invite_sent": "Invitación enviada",
  "log.title": "Registrar partido", "log.team_a": "Equipo A", "log.team_b": "Equipo B",
  "log.location": "Lugar", "log.location_ph": "Rucker Park", "log.players_stats": "Jugadores y stats",
  "log.no_members": "Aún sin miembros — comparte el código.",
  "log.save": "Guardar partido", "log.pick_2": "Elige al menos 2 jugadores",
  "log.each_team": "Cada equipo necesita un jugador", "log.logged": "Partido registrado 🏀",
  "drills.title": "Ejercicios de tiro", "drills.private": "Privado — solo tú lo ves.",
  "drills.selected": "Zona seleccionada", "drills.no_attempts": "Sin intentos aún",
  "drills.made": "Anotados", "drills.attempts": "Intentos", "drills.log": "Registrar tiros",
  "drills.history": "Historial", "drills.empty": "Sin ejercicios — elige un punto y registra el primero.",
  "drills.logged": "Ejercicio registrado", "drills.removed": "Eliminado",
  "drills.makes_exceed": "Anotados no pueden superar intentos",
  "auth.tag": "Vuelve a la cancha. Encuentra tu próxima pachanga.",
  "auth.signup": "Registro", "auth.login": "Acceso",
  "auth.email": "Email", "auth.password": "Contraseña",
  "auth.lace_up": "Atar cordones", "auth.check_in": "Entrar",
  "auth.terms": "Al registrarte aceptas compartir tu ubicación y recibir notificaciones.",
  "auth.welcome": "Bienvenido a Hoops 🏀",
  "auth.username_taken": "Usuario ya en uso", "auth.phone_used": "Teléfono ya en uso",
  "toast.failed": "Error", "toast.something": "Algo falló", "toast.court_added": "Cancha añadida en tu ubicación",
  "nf.title": "Fuera de los límites", "nf.sub": "Esa página no está en la cancha.", "nf.back": "Volver a Hoops",
  "err.title": "Tiro fallado.", "err.try": "Reintentar",
};

const de: Dict = {
  "nav.court": "Court", "nav.leagues": "Ligen", "nav.profile": "Profil",
  "common.back": "Zurück", "common.loading": "Laden…", "common.save": "Speichern", "common.cancel": "Abbrechen",
  "common.close": "Schließen", "common.create": "Erstellen", "common.delete": "Löschen", "common.optional": "optional",
  "common.opt": "opt.", "common.away": "entfernt", "common.skip": "Überspringen",
  "settings.title": "Einstellungen", "settings.appearance": "Darstellung", "settings.language": "Sprache",
  "settings.day": "Tagmodus", "settings.night": "Nachtmodus",
  "settings.radius": "Such-Radius", "settings.radius.courts": "Courts innerhalb", "settings.radius.hoopers": "Spieler innerhalb",
  "lang.pick.title": "Wähle deine Sprache", "lang.pick.sub": "Du kannst dies später in den Einstellungen ändern.", "lang.continue": "Weiter",
  "home.live": "Live", "home.off": "Aus", "home.on": "An",
  "home.hoopers_nearby": "Spieler in der Nähe", "home.active_courts": "Aktive Courts",
  "home.courts_near": "Courts in deiner Nähe", "home.add": "Hinzufügen",
  "home.mark_first": "Markiere deinen ersten Court", "home.hooper": "Spieler", "home.hoopers": "Spieler",
  "home.hoopers_near": "Spieler in deiner Nähe",
  "home.empty.title": "Court ist leer", "home.empty.sub": "Noch keine Spieler in der Nähe. Lade Freunde ein.",
  "home.court.mark": "Court markieren", "home.court.pinned": "An deiner aktuellen Position.",
  "home.court.name_ph": "Court-Name (z.B. Westpark)", "home.court.add_btn": "Court hinzufügen", "home.court.saving": "Speichern…",
  "home.gmaps": "Google Maps", "home.here": "hier",
  "player.location_unknown": "Standort unbekannt", "player.rating": "Bewertung", "player.ratings": "Bewertungen",
  "player.callup": "🏀 Zum Spielen einladen", "player.invite": "Einladen", "player.invite_to": "Einladen",
  "player.send_invite": "Einladung senden",
  "player.cant_rate": "Du kannst diesen Spieler bewerten, nachdem ihr zusammen gespielt habt oder er deine Einladung annimmt.",
  "player.update_rating": "Bewertung aktualisieren", "player.rate": "Spieler bewerten", "player.how_hoop": "Spielstil",
  "player.offense": "Offense", "player.defense": "Defense", "player.save_rating": "Bewertung speichern",
  "player.invite_default": "Lust auf ein Spiel? 🏀", "player.invite_ph": "Court, Zeit, Vibe…",
  "player.back_court": "Zurück zum Court", "player.invite_sent": "Einladung gesendet",
  "profile.username": "Benutzername", "profile.phone": "Telefon", "profile.height": "Größe (cm)",
  "profile.vertical": "Sprunghöhe (cm)", "profile.weight": "Gewicht (kg)", "profile.playstyle": "Spielstil",
  "profile.visible": "sichtbar", "profile.pick_archetype": "Archetyp wählen",
  "profile.preferred_game": "Bevorzugter Spieltyp", "profile.pick_one": "Wähle",
  "profile.shooting_drills": "Wurfübungen", "profile.signout": "Abmelden", "profile.saved": "Profil gespeichert",
  "leagues.title": "LIGEN", "leagues.sub": "Spiel mit deiner Crew. Tracke jeden Sieg.",
  "leagues.invites": "Einladungen", "leagues.from": "von",
  "leagues.accept": "Annehmen", "leagues.decline": "Ablehnen",
  "leagues.create": "Liga erstellen", "leagues.join_code": "Mit Code beitreten",
  "leagues.your": "Deine Ligen", "leagues.none": "Noch keine Ligen",
  "leagues.none_sub": "Erstelle eine mit deiner Crew oder tritt mit Code bei.",
  "leagues.code": "Code", "leagues.new": "Neue Liga", "leagues.name": "Liga-Name",
  "leagues.name_ph": "Sonntags-Spiel", "leagues.join": "Liga beitreten", "leagues.join_field": "Beitritts-Code",
  "leagues.join_btn": "Beitreten", "leagues.joined": "Liga beigetreten", "leagues.created": "Liga erstellt",
  "leagues.declined": "Abgelehnt", "leagues.not_found": "Liga nicht gefunden",
  "leagues.invalid_code": "Ungültiger Code", "leagues.name_short": "Name zu kurz",
  "ld.code_copied": "Code kopiert", "ld.log_game": "Spiel eintragen", "ld.game_type": "Spieltyp", "ld.all": "Alle",
  "ld.show_lb": "Zeige {type}-Rangliste.",
  "ld.koth_note": "King of the Hill — nur Einzelstatistiken.",
  "ld.tab_players": "Spieler", "ld.tab_teams": "Teams", "ld.tab_games": "Spiele",
  "ld.no_stats": "Noch keine Stats — trage dein erstes Spiel ein.",
  "ld.no_team_records": "Noch keine Team-Records.", "ld.no_games": "Noch keine Spiele eingetragen.",
  "ld.invite_players": "Spieler einladen", "ld.search_user": "Benutzername suchen…",
  "ld.type_2": "Mindestens 2 Zeichen eingeben.", "ld.no_match": "Keine Treffer.",
  "ld.invite": "Einladen", "ld.already_invited": "Bereits eingeladen", "ld.invite_sent": "Einladung gesendet",
  "log.title": "Spiel eintragen", "log.team_a": "Team A", "log.team_b": "Team B",
  "log.location": "Ort", "log.location_ph": "Rucker Park", "log.players_stats": "Spieler & Stats",
  "log.no_members": "Noch keine Mitglieder — teile den Code.",
  "log.save": "Spiel speichern", "log.pick_2": "Wähle mindestens 2 Spieler",
  "log.each_team": "Jedes Team braucht einen Spieler", "log.logged": "Spiel gespeichert 🏀",
  "drills.title": "Wurfübungen", "drills.private": "Privat — nur du siehst das.",
  "drills.selected": "Ausgewählte Zone", "drills.no_attempts": "Noch keine Versuche",
  "drills.made": "Treffer", "drills.attempts": "Versuche", "drills.log": "Würfe eintragen",
  "drills.history": "Verlauf", "drills.empty": "Noch keine Übungen — wähle einen Spot und trage ein.",
  "drills.logged": "Übung eingetragen", "drills.removed": "Entfernt",
  "drills.makes_exceed": "Treffer dürfen Versuche nicht übersteigen",
  "auth.tag": "Spiel weiter. Finde deine nächste Session.",
  "auth.signup": "Registrieren", "auth.login": "Anmelden",
  "auth.email": "E-Mail", "auth.password": "Passwort",
  "auth.lace_up": "Schnüren", "auth.check_in": "Einchecken",
  "auth.terms": "Mit der Registrierung stimmst du zu, deinen Standort zu teilen und Benachrichtigungen zu erhalten.",
  "auth.welcome": "Willkommen bei Hoops 🏀",
  "auth.username_taken": "Benutzername vergeben", "auth.phone_used": "Telefonnummer bereits verwendet",
  "toast.failed": "Fehler", "toast.something": "Etwas ist schiefgelaufen", "toast.court_added": "Court an deinem Standort hinzugefügt",
  "nf.title": "Im Aus", "nf.sub": "Diese Seite ist nicht auf dem Court.", "nf.back": "Zurück zu Hoops",
  "err.title": "Airball.", "err.try": "Erneut versuchen",
};

const fr: Dict = {
  "nav.court": "Terrain", "nav.leagues": "Ligues", "nav.profile": "Profil",
  "common.back": "Retour", "common.loading": "Chargement…", "common.save": "Enregistrer", "common.cancel": "Annuler",
  "common.close": "Fermer", "common.create": "Créer", "common.delete": "Supprimer", "common.optional": "optionnel",
  "common.opt": "opt.", "common.away": "de distance", "common.skip": "Passer",
  "settings.title": "Paramètres", "settings.appearance": "Apparence", "settings.language": "Langue",
  "settings.day": "Mode jour", "settings.night": "Mode nuit",
  "settings.radius": "Rayon de recherche", "settings.radius.courts": "Terrains à moins de", "settings.radius.hoopers": "Joueurs à moins de",
  "lang.pick.title": "Choisis ta langue", "lang.pick.sub": "Tu peux changer cela plus tard dans les Paramètres.", "lang.continue": "Continuer",
  "home.live": "Live", "home.off": "Off", "home.on": "On",
  "home.hoopers_nearby": "Joueurs à proximité", "home.active_courts": "Terrains actifs",
  "home.courts_near": "Terrains près de toi", "home.add": "Ajouter",
  "home.mark_first": "Marque ton premier terrain", "home.hooper": "joueur", "home.hoopers": "joueurs",
  "home.hoopers_near": "Joueurs près de toi",
  "home.empty.title": "Terrain vide", "home.empty.sub": "Aucun joueur autour. Invite des amis sur Hoops.",
  "home.court.mark": "Marquer un terrain", "home.court.pinned": "Épinglé à ta position actuelle.",
  "home.court.name_ph": "Nom du terrain (ex. West Park)", "home.court.add_btn": "Ajouter le terrain", "home.court.saving": "Enregistrement…",
  "home.gmaps": "Google Maps", "home.here": "ici",
  "player.location_unknown": "Lieu inconnu", "player.rating": "note", "player.ratings": "notes",
  "player.callup": "🏀 Appeler pour jouer", "player.invite": "Inviter", "player.invite_to": "Inviter",
  "player.send_invite": "Envoyer l'invitation",
  "player.cant_rate": "Tu peux noter ce joueur après avoir joué ensemble ou s'il accepte ton invitation.",
  "player.update_rating": "Mettre à jour la note", "player.rate": "Noter ce joueur", "player.how_hoop": "Son jeu",
  "player.offense": "Attaque", "player.defense": "Défense", "player.save_rating": "Enregistrer la note",
  "player.invite_default": "On joue ? 🏀", "player.invite_ph": "Terrain, heure, ambiance…",
  "player.back_court": "Retour au terrain", "player.invite_sent": "Invitation envoyée",
  "profile.username": "Pseudo", "profile.phone": "Téléphone", "profile.height": "Taille (cm)",
  "profile.vertical": "Détente (cm)", "profile.weight": "Poids (kg)", "profile.playstyle": "Style de jeu",
  "profile.visible": "visible", "profile.pick_archetype": "Choisis ton archétype",
  "profile.preferred_game": "Type de partie préféré", "profile.pick_one": "Choisis",
  "profile.shooting_drills": "Exercices de tir", "profile.signout": "Se déconnecter", "profile.saved": "Profil enregistré",
  "leagues.title": "LIGUES", "leagues.sub": "Joue avec ton crew. Suis chaque victoire.",
  "leagues.invites": "Invitations", "leagues.from": "de",
  "leagues.accept": "Accepter", "leagues.decline": "Refuser",
  "leagues.create": "Créer une ligue", "leagues.join_code": "Rejoindre avec un code",
  "leagues.your": "Tes ligues", "leagues.none": "Aucune ligue",
  "leagues.none_sub": "Crée-en une avec ton crew ou rejoins avec un code.",
  "leagues.code": "Code", "leagues.new": "Nouvelle ligue", "leagues.name": "Nom de la ligue",
  "leagues.name_ph": "Match du dimanche", "leagues.join": "Rejoindre une ligue", "leagues.join_field": "Code",
  "leagues.join_btn": "Rejoindre", "leagues.joined": "Ligue rejointe", "leagues.created": "Ligue créée",
  "leagues.declined": "Refusée", "leagues.not_found": "Ligue introuvable",
  "leagues.invalid_code": "Code invalide", "leagues.name_short": "Nom trop court",
  "ld.code_copied": "Code copié", "ld.log_game": "Enregistrer un match", "ld.game_type": "Type", "ld.all": "Tous",
  "ld.show_lb": "Classement {type} affiché.",
  "ld.koth_note": "King of the Hill — stats individuelles uniquement.",
  "ld.tab_players": "Joueurs", "ld.tab_teams": "Équipes", "ld.tab_games": "Matchs",
  "ld.no_stats": "Pas encore de stats — enregistre ton premier match.",
  "ld.no_team_records": "Pas encore de records d'équipe.", "ld.no_games": "Aucun match enregistré.",
  "ld.invite_players": "Inviter des joueurs", "ld.search_user": "Rechercher un pseudo…",
  "ld.type_2": "Tape au moins 2 caractères.", "ld.no_match": "Aucun résultat.",
  "ld.invite": "Inviter", "ld.already_invited": "Déjà invité", "ld.invite_sent": "Invitation envoyée",
  "log.title": "Enregistrer un match", "log.team_a": "Équipe A", "log.team_b": "Équipe B",
  "log.location": "Lieu", "log.location_ph": "Rucker Park", "log.players_stats": "Joueurs & stats",
  "log.no_members": "Pas encore de membres — partage le code.",
  "log.save": "Enregistrer le match", "log.pick_2": "Choisis au moins 2 joueurs",
  "log.each_team": "Chaque équipe a besoin d'un joueur", "log.logged": "Match enregistré 🏀",
  "drills.title": "Exercices de tir", "drills.private": "Privé — toi seul vois ça.",
  "drills.selected": "Zone sélectionnée", "drills.no_attempts": "Aucun essai",
  "drills.made": "Réussis", "drills.attempts": "Essais", "drills.log": "Enregistrer les tirs",
  "drills.history": "Historique", "drills.empty": "Aucun exercice — choisis un spot et enregistre.",
  "drills.logged": "Exercice enregistré", "drills.removed": "Supprimé",
  "drills.makes_exceed": "Les réussis ne peuvent dépasser les essais",
  "auth.tag": "Reviens jouer. Trouve ta prochaine session.",
  "auth.signup": "Inscription", "auth.login": "Connexion",
  "auth.email": "E-mail", "auth.password": "Mot de passe",
  "auth.lace_up": "Lacer", "auth.check_in": "Entrer",
  "auth.terms": "En t'inscrivant tu acceptes de partager ta position et de recevoir des notifications.",
  "auth.welcome": "Bienvenue sur Hoops 🏀",
  "auth.username_taken": "Pseudo déjà pris", "auth.phone_used": "Téléphone déjà utilisé",
  "toast.failed": "Échec", "toast.something": "Une erreur est survenue", "toast.court_added": "Terrain ajouté à ta position",
  "nf.title": "Hors limites", "nf.sub": "Cette page n'est pas sur le terrain.", "nf.back": "Retour à Hoops",
  "err.title": "Airball.", "err.try": "Réessayer",
};

const it: Dict = {
  "nav.court": "Campo", "nav.leagues": "Leghe", "nav.profile": "Profilo",
  "common.back": "Indietro", "common.loading": "Caricamento…", "common.save": "Salva", "common.cancel": "Annulla",
  "common.close": "Chiudi", "common.create": "Crea", "common.delete": "Elimina", "common.optional": "opzionale",
  "common.opt": "opz.", "common.away": "di distanza", "common.skip": "Salta",
  "settings.title": "Impostazioni", "settings.appearance": "Aspetto", "settings.language": "Lingua",
  "settings.day": "Modalità giorno", "settings.night": "Modalità notte",
  "settings.radius": "Raggio di ricerca", "settings.radius.courts": "Campi entro", "settings.radius.hoopers": "Giocatori entro",
  "lang.pick.title": "Scegli la tua lingua", "lang.pick.sub": "Puoi cambiarla in seguito nelle Impostazioni.", "lang.continue": "Continua",
  "home.live": "Live", "home.off": "Off", "home.on": "On",
  "home.hoopers_nearby": "Giocatori vicini", "home.active_courts": "Campi attivi",
  "home.courts_near": "Campi vicino a te", "home.add": "Aggiungi",
  "home.mark_first": "Segna il tuo primo campo", "home.hooper": "giocatore", "home.hoopers": "giocatori",
  "home.hoopers_near": "Giocatori vicino a te",
  "home.empty.title": "Campo vuoto", "home.empty.sub": "Nessun giocatore vicino. Invita amici su Hoops.",
  "home.court.mark": "Segna un campo", "home.court.pinned": "Fissato alla tua posizione attuale.",
  "home.court.name_ph": "Nome del campo (es. Parco Ovest)", "home.court.add_btn": "Aggiungi campo", "home.court.saving": "Salvataggio…",
  "home.gmaps": "Google Maps", "home.here": "qui",
  "player.location_unknown": "Posizione sconosciuta", "player.rating": "valutazione", "player.ratings": "valutazioni",
  "player.callup": "🏀 Chiama per giocare", "player.invite": "Invita", "player.invite_to": "Invita",
  "player.send_invite": "Invia invito",
  "player.cant_rate": "Puoi valutare questo giocatore dopo aver giocato insieme o se accetta il tuo invito.",
  "player.update_rating": "Aggiorna valutazione", "player.rate": "Valuta giocatore", "player.how_hoop": "Come gioca",
  "player.offense": "Attacco", "player.defense": "Difesa", "player.save_rating": "Salva valutazione",
  "player.invite_default": "Giochiamo? 🏀", "player.invite_ph": "Campo, ora, vibe…",
  "player.back_court": "Torna al campo", "player.invite_sent": "Invito inviato",
  "profile.username": "Username", "profile.phone": "Telefono", "profile.height": "Altezza (cm)",
  "profile.vertical": "Salto verticale (cm)", "profile.weight": "Peso (kg)", "profile.playstyle": "Stile di gioco",
  "profile.visible": "visibile", "profile.pick_archetype": "Scegli l'archetipo",
  "profile.preferred_game": "Tipo di partita preferito", "profile.pick_one": "Scegli",
  "profile.shooting_drills": "Esercizi di tiro", "profile.signout": "Esci", "profile.saved": "Profilo salvato",
  "leagues.title": "LEGHE", "leagues.sub": "Gioca col tuo crew. Tieni traccia di ogni vittoria.",
  "leagues.invites": "Inviti", "leagues.from": "da",
  "leagues.accept": "Accetta", "leagues.decline": "Rifiuta",
  "leagues.create": "Crea lega", "leagues.join_code": "Unisciti con codice",
  "leagues.your": "Le tue leghe", "leagues.none": "Nessuna lega",
  "leagues.none_sub": "Creane una col tuo crew o unisciti con un codice.",
  "leagues.code": "Codice", "leagues.new": "Nuova lega", "leagues.name": "Nome della lega",
  "leagues.name_ph": "Partita della domenica", "leagues.join": "Unisciti a una lega", "leagues.join_field": "Codice",
  "leagues.join_btn": "Unisciti", "leagues.joined": "Ti sei unito alla lega", "leagues.created": "Lega creata",
  "leagues.declined": "Rifiutato", "leagues.not_found": "Lega non trovata",
  "leagues.invalid_code": "Codice non valido", "leagues.name_short": "Nome troppo corto",
  "ld.code_copied": "Codice copiato", "ld.log_game": "Registra partita", "ld.game_type": "Tipo", "ld.all": "Tutte",
  "ld.show_lb": "Classifica {type} mostrata.",
  "ld.koth_note": "King of the Hill — solo statistiche individuali.",
  "ld.tab_players": "Giocatori", "ld.tab_teams": "Squadre", "ld.tab_games": "Partite",
  "ld.no_stats": "Nessuna stat — registra la prima partita.",
  "ld.no_team_records": "Nessun record di squadra.", "ld.no_games": "Nessuna partita registrata.",
  "ld.invite_players": "Invita giocatori", "ld.search_user": "Cerca username…",
  "ld.type_2": "Scrivi almeno 2 caratteri.", "ld.no_match": "Nessun risultato.",
  "ld.invite": "Invita", "ld.already_invited": "Già invitato", "ld.invite_sent": "Invito inviato",
  "log.title": "Registra partita", "log.team_a": "Squadra A", "log.team_b": "Squadra B",
  "log.location": "Luogo", "log.location_ph": "Rucker Park", "log.players_stats": "Giocatori e stat",
  "log.no_members": "Nessun membro — condividi il codice.",
  "log.save": "Salva partita", "log.pick_2": "Scegli almeno 2 giocatori",
  "log.each_team": "Ogni squadra ha bisogno di un giocatore", "log.logged": "Partita registrata 🏀",
  "drills.title": "Esercizi di tiro", "drills.private": "Privato — solo tu lo vedi.",
  "drills.selected": "Zona selezionata", "drills.no_attempts": "Nessun tentativo",
  "drills.made": "Realizzati", "drills.attempts": "Tentativi", "drills.log": "Registra tiri",
  "drills.history": "Cronologia", "drills.empty": "Nessun esercizio — scegli uno spot e registra.",
  "drills.logged": "Esercizio registrato", "drills.removed": "Rimosso",
  "drills.makes_exceed": "I realizzati non possono superare i tentativi",
  "auth.tag": "Torna a giocare. Trova la prossima partita.",
  "auth.signup": "Registrati", "auth.login": "Accedi",
  "auth.email": "Email", "auth.password": "Password",
  "auth.lace_up": "Allaccia", "auth.check_in": "Entra",
  "auth.terms": "Registrandoti accetti di condividere la posizione e ricevere notifiche.",
  "auth.welcome": "Benvenuto su Hoops 🏀",
  "auth.username_taken": "Username già in uso", "auth.phone_used": "Telefono già in uso",
  "toast.failed": "Errore", "toast.something": "Qualcosa è andato storto", "toast.court_added": "Campo aggiunto alla tua posizione",
  "nf.title": "Fuori campo", "nf.sub": "Quella pagina non è sul campo.", "nf.back": "Torna a Hoops",
  "err.title": "Airball.", "err.try": "Riprova",
};

const DICTS: Record<Lang, Dict> = { en, hr, es, de, fr, it };

const STORAGE_KEY = "hoops-lang";

type Ctx = {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string, vars?: Record<string, string>) => string;
  needsPick: boolean;
  confirmPick: () => void;
};
const LangContext = createContext<Ctx>({
  lang: "en",
  setLang: () => {},
  t: (k) => k,
  needsPick: false,
  confirmPick: () => {},
});

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>("en");
  const [needsPick, setNeedsPick] = useState(false);

  useEffect(() => {
    if (typeof window === "undefined") return;
    const stored = localStorage.getItem(STORAGE_KEY) as Lang | null;
    if (stored && DICTS[stored]) {
      setLangState(stored);
    } else {
      const browser = (navigator.language || "en").slice(0, 2).toLowerCase() as Lang;
      if (DICTS[browser]) setLangState(browser);
      setNeedsPick(true);
    }
  }, []);

  function setLang(l: Lang) {
    setLangState(l);
    if (typeof window !== "undefined") localStorage.setItem(STORAGE_KEY, l);
  }
  function confirmPick() {
    if (typeof window !== "undefined") localStorage.setItem(STORAGE_KEY, lang);
    setNeedsPick(false);
  }
  function t(key: string, vars?: Record<string, string>) {
    let s = DICTS[lang]?.[key] ?? DICTS.en[key] ?? key;
    if (vars) for (const [k, v] of Object.entries(vars)) s = s.replace(`{${k}}`, v);
    return s;
  }

  return (
    <LangContext.Provider value={{ lang, setLang, t, needsPick, confirmPick }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);
