/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppShootingLabRouteImport } from './routes/app.shooting-lab'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppDrillsRouteImport } from './routes/app.drills'
import { Route as AppMessagesIndexRouteImport } from './routes/app.messages.index'
import { Route as AppLeaguesIndexRouteImport } from './routes/app.leagues.index'
import { Route as AppPlayerIdRouteImport } from './routes/app.player.$id'
import { Route as AppMessagesUserIdRouteImport } from './routes/app.messages.$userId'
import { Route as AppLeaguesIdRouteImport } from './routes/app.leagues.$id'
import { Route as AppLeaguesIdIndexRouteImport } from './routes/app.leagues.$id.index'
import { Route as AppLeaguesIdLogRouteImport } from './routes/app.leagues.$id.log'
import { Route as AppLeaguesIdChatRouteImport } from './routes/app.leagues.$id.chat'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppShootingLabRoute = AppShootingLabRouteImport.update({
  id: '/shooting-lab',
  path: '/shooting-lab',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDrillsRoute = AppDrillsRouteImport.update({
  id: '/drills',
  path: '/drills',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesIndexRoute = AppMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaguesIndexRoute = AppLeaguesIndexRouteImport.update({
  id: '/leagues/',
  path: '/leagues/',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayerIdRoute = AppPlayerIdRouteImport.update({
  id: '/player/$id',
  path: '/player/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesUserIdRoute = AppMessagesUserIdRouteImport.update({
  id: '/messages/$userId',
  path: '/messages/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaguesIdRoute = AppLeaguesIdRouteImport.update({
  id: '/leagues/$id',
  path: '/leagues/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaguesIdIndexRoute = AppLeaguesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLeaguesIdRoute,
} as any)
const AppLeaguesIdLogRoute = AppLeaguesIdLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AppLeaguesIdRoute,
} as any)
const AppLeaguesIdChatRoute = AppLeaguesIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppLeaguesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/drills': typeof AppDrillsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shooting-lab': typeof AppShootingLabRoute
  '/app/': typeof AppIndexRoute
  '/app/leagues/$id': typeof AppLeaguesIdRouteWithChildren
  '/app/messages/$userId': typeof AppMessagesUserIdRoute
  '/app/player/$id': typeof AppPlayerIdRoute
  '/app/leagues/': typeof AppLeaguesIndexRoute
  '/app/messages/': typeof AppMessagesIndexRoute
  '/app/leagues/$id/chat': typeof AppLeaguesIdChatRoute
  '/app/leagues/$id/log': typeof AppLeaguesIdLogRoute
  '/app/leagues/$id/': typeof AppLeaguesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/drills': typeof AppDrillsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shooting-lab': typeof AppShootingLabRoute
  '/app': typeof AppIndexRoute
  '/app/messages/$userId': typeof AppMessagesUserIdRoute
  '/app/player/$id': typeof AppPlayerIdRoute
  '/app/leagues': typeof AppLeaguesIndexRoute
  '/app/messages': typeof AppMessagesIndexRoute
  '/app/leagues/$id/chat': typeof AppLeaguesIdChatRoute
  '/app/leagues/$id/log': typeof AppLeaguesIdLogRoute
  '/app/leagues/$id': typeof AppLeaguesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/drills': typeof AppDrillsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shooting-lab': typeof AppShootingLabRoute
  '/app/': typeof AppIndexRoute
  '/app/leagues/$id': typeof AppLeaguesIdRouteWithChildren
  '/app/messages/$userId': typeof AppMessagesUserIdRoute
  '/app/player/$id': typeof AppPlayerIdRoute
  '/app/leagues/': typeof AppLeaguesIndexRoute
  '/app/messages/': typeof AppMessagesIndexRoute
  '/app/leagues/$id/chat': typeof AppLeaguesIdChatRoute
  '/app/leagues/$id/log': typeof AppLeaguesIdLogRoute
  '/app/leagues/$id/': typeof AppLeaguesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/drills'
    | '/app/profile'
    | '/app/settings'
    | '/app/shooting-lab'
    | '/app/'
    | '/app/leagues/$id'
    | '/app/messages/$userId'
    | '/app/player/$id'
    | '/app/leagues/'
    | '/app/messages/'
    | '/app/leagues/$id/chat'
    | '/app/leagues/$id/log'
    | '/app/leagues/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/drills'
    | '/app/profile'
    | '/app/settings'
    | '/app/shooting-lab'
    | '/app'
    | '/app/messages/$userId'
    | '/app/player/$id'
    | '/app/leagues'
    | '/app/messages'
    | '/app/leagues/$id/chat'
    | '/app/leagues/$id/log'
    | '/app/leagues/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/drills'
    | '/app/profile'
    | '/app/settings'
    | '/app/shooting-lab'
    | '/app/'
    | '/app/leagues/$id'
    | '/app/messages/$userId'
    | '/app/player/$id'
    | '/app/leagues/'
    | '/app/messages/'
    | '/app/leagues/$id/chat'
    | '/app/leagues/$id/log'
    | '/app/leagues/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/shooting-lab': {
      id: '/app/shooting-lab'
      path: '/shooting-lab'
      fullPath: '/app/shooting-lab'
      preLoaderRoute: typeof AppShootingLabRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/drills': {
      id: '/app/drills'
      path: '/drills'
      fullPath: '/app/drills'
      preLoaderRoute: typeof AppDrillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages/': {
      id: '/app/messages/'
      path: '/messages'
      fullPath: '/app/messages/'
      preLoaderRoute: typeof AppMessagesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leagues/': {
      id: '/app/leagues/'
      path: '/leagues'
      fullPath: '/app/leagues/'
      preLoaderRoute: typeof AppLeaguesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/player/$id': {
      id: '/app/player/$id'
      path: '/player/$id'
      fullPath: '/app/player/$id'
      preLoaderRoute: typeof AppPlayerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages/$userId': {
      id: '/app/messages/$userId'
      path: '/messages/$userId'
      fullPath: '/app/messages/$userId'
      preLoaderRoute: typeof AppMessagesUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leagues/$id': {
      id: '/app/leagues/$id'
      path: '/leagues/$id'
      fullPath: '/app/leagues/$id'
      preLoaderRoute: typeof AppLeaguesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leagues/$id/': {
      id: '/app/leagues/$id/'
      path: '/'
      fullPath: '/app/leagues/$id/'
      preLoaderRoute: typeof AppLeaguesIdIndexRouteImport
      parentRoute: typeof AppLeaguesIdRoute
    }
    '/app/leagues/$id/log': {
      id: '/app/leagues/$id/log'
      path: '/log'
      fullPath: '/app/leagues/$id/log'
      preLoaderRoute: typeof AppLeaguesIdLogRouteImport
      parentRoute: typeof AppLeaguesIdRoute
    }
    '/app/leagues/$id/chat': {
      id: '/app/leagues/$id/chat'
      path: '/chat'
      fullPath: '/app/leagues/$id/chat'
      preLoaderRoute: typeof AppLeaguesIdChatRouteImport
      parentRoute: typeof AppLeaguesIdRoute
    }
  }
}

interface AppLeaguesIdRouteChildren {
  AppLeaguesIdChatRoute: typeof AppLeaguesIdChatRoute
  AppLeaguesIdLogRoute: typeof AppLeaguesIdLogRoute
  AppLeaguesIdIndexRoute: typeof AppLeaguesIdIndexRoute
}

const AppLeaguesIdRouteChildren: AppLeaguesIdRouteChildren = {
  AppLeaguesIdChatRoute: AppLeaguesIdChatRoute,
  AppLeaguesIdLogRoute: AppLeaguesIdLogRoute,
  AppLeaguesIdIndexRoute: AppLeaguesIdIndexRoute,
}

const AppLeaguesIdRouteWithChildren = AppLeaguesIdRoute._addFileChildren(
  AppLeaguesIdRouteChildren,
)

interface AppRouteChildren {
  AppDrillsRoute: typeof AppDrillsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShootingLabRoute: typeof AppShootingLabRoute
  AppIndexRoute: typeof AppIndexRoute
  AppLeaguesIdRoute: typeof AppLeaguesIdRouteWithChildren
  AppMessagesUserIdRoute: typeof AppMessagesUserIdRoute
  AppPlayerIdRoute: typeof AppPlayerIdRoute
  AppLeaguesIndexRoute: typeof AppLeaguesIndexRoute
  AppMessagesIndexRoute: typeof AppMessagesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDrillsRoute: AppDrillsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShootingLabRoute: AppShootingLabRoute,
  AppIndexRoute: AppIndexRoute,
  AppLeaguesIdRoute: AppLeaguesIdRouteWithChildren,
  AppMessagesUserIdRoute: AppMessagesUserIdRoute,
  AppPlayerIdRoute: AppPlayerIdRoute,
  AppLeaguesIndexRoute: AppLeaguesIndexRoute,
  AppMessagesIndexRoute: AppMessagesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
