/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppDrillsRouteImport } from './routes/app.drills'
import { Route as AppLeaguesIndexRouteImport } from './routes/app.leagues.index'
import { Route as AppPlayerIdRouteImport } from './routes/app.player.$id'
import { Route as AppLeaguesIdRouteImport } from './routes/app.leagues.$id'
import { Route as AppLeaguesIdLogRouteImport } from './routes/app.leagues.$id.log'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDrillsRoute = AppDrillsRouteImport.update({
  id: '/drills',
  path: '/drills',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaguesIndexRoute = AppLeaguesIndexRouteImport.update({
  id: '/leagues/',
  path: '/leagues/',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayerIdRoute = AppPlayerIdRouteImport.update({
  id: '/player/$id',
  path: '/player/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaguesIdRoute = AppLeaguesIdRouteImport.update({
  id: '/leagues/$id',
  path: '/leagues/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaguesIdLogRoute = AppLeaguesIdLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AppLeaguesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/drills': typeof AppDrillsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/leagues/$id': typeof AppLeaguesIdRouteWithChildren
  '/app/player/$id': typeof AppPlayerIdRoute
  '/app/leagues/': typeof AppLeaguesIndexRoute
  '/app/leagues/$id/log': typeof AppLeaguesIdLogRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/drills': typeof AppDrillsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/leagues/$id': typeof AppLeaguesIdRouteWithChildren
  '/app/player/$id': typeof AppPlayerIdRoute
  '/app/leagues': typeof AppLeaguesIndexRoute
  '/app/leagues/$id/log': typeof AppLeaguesIdLogRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/drills': typeof AppDrillsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/leagues/$id': typeof AppLeaguesIdRouteWithChildren
  '/app/player/$id': typeof AppPlayerIdRoute
  '/app/leagues/': typeof AppLeaguesIndexRoute
  '/app/leagues/$id/log': typeof AppLeaguesIdLogRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/drills'
    | '/app/profile'
    | '/app/settings'
    | '/app/'
    | '/app/leagues/$id'
    | '/app/player/$id'
    | '/app/leagues/'
    | '/app/leagues/$id/log'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/drills'
    | '/app/profile'
    | '/app/settings'
    | '/app'
    | '/app/leagues/$id'
    | '/app/player/$id'
    | '/app/leagues'
    | '/app/leagues/$id/log'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/drills'
    | '/app/profile'
    | '/app/settings'
    | '/app/'
    | '/app/leagues/$id'
    | '/app/player/$id'
    | '/app/leagues/'
    | '/app/leagues/$id/log'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/drills': {
      id: '/app/drills'
      path: '/drills'
      fullPath: '/app/drills'
      preLoaderRoute: typeof AppDrillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leagues/': {
      id: '/app/leagues/'
      path: '/leagues'
      fullPath: '/app/leagues/'
      preLoaderRoute: typeof AppLeaguesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/player/$id': {
      id: '/app/player/$id'
      path: '/player/$id'
      fullPath: '/app/player/$id'
      preLoaderRoute: typeof AppPlayerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leagues/$id': {
      id: '/app/leagues/$id'
      path: '/leagues/$id'
      fullPath: '/app/leagues/$id'
      preLoaderRoute: typeof AppLeaguesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leagues/$id/log': {
      id: '/app/leagues/$id/log'
      path: '/log'
      fullPath: '/app/leagues/$id/log'
      preLoaderRoute: typeof AppLeaguesIdLogRouteImport
      parentRoute: typeof AppLeaguesIdRoute
    }
  }
}

interface AppLeaguesIdRouteChildren {
  AppLeaguesIdLogRoute: typeof AppLeaguesIdLogRoute
}

const AppLeaguesIdRouteChildren: AppLeaguesIdRouteChildren = {
  AppLeaguesIdLogRoute: AppLeaguesIdLogRoute,
}

const AppLeaguesIdRouteWithChildren = AppLeaguesIdRoute._addFileChildren(
  AppLeaguesIdRouteChildren,
)

interface AppRouteChildren {
  AppDrillsRoute: typeof AppDrillsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppLeaguesIdRoute: typeof AppLeaguesIdRouteWithChildren
  AppPlayerIdRoute: typeof AppPlayerIdRoute
  AppLeaguesIndexRoute: typeof AppLeaguesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDrillsRoute: AppDrillsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppLeaguesIdRoute: AppLeaguesIdRouteWithChildren,
  AppPlayerIdRoute: AppPlayerIdRoute,
  AppLeaguesIndexRoute: AppLeaguesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
